---
- import_playbook: define_libvirt_host.yml

- hosts: libvirt_host
  tasks:
    - name: Create specified Virtual Networks
      include_role:
        name: sle_micro_vnet
        tasks_from: create_vnet.yml
      loop_control:
        loop_var: vnet_config
      loop: "{{ vnet_configs }}"
