---
- import_playbook: define_sle_micro_vms_group.yml

- name: Setup SSH on sle_micro VMs for user {{ vm_mgmt_user }}
  hosts: sle_micro_vms
  gather_facts: false
  tasks:
    - name: Determine set of required packages
      ansible.builtin.set_fact:
        required_packages: >-
          {%- set _pkgs=[] -%}
          {%- if sle_micro_packages is defined -%}
          {%-   set _ = _pkgs.extend(sle_micro_packages.required | default([])) -%}
          {%- endif -%}
          {%- for w in sle_micro_workloads | default(sle_micro_defaults.workloads) -%}
          {%-   set _ = _pkgs.extend(w.packages | default([])) -%}
          {%- endfor -%}
          {{- _pkgs -}}

    - name: Install required packages
      become: true
      ansible.builtin.package:
        name: "{{ required_packages }}"
        state: present
      register: sle_micro_required_packages

    - name: Reboot if required
      become: true
      reboot:
      when:
        - sle_micro_required_packages is changed
