---
- name: Create cache dir
  ansible.builtin.file:
    path: "{{ sle_micro.cache.images }}"
    state: directory
    mode: "0755"

- name: Download sle_micro image to cache
  ansible.builtin.copy:
    dest: "{{ sle_micro_image.cached }}"
    src: "{{ sle_micro_image.path }}"
    mode: "0644"
  register: sle_micro_image_download

- name: Report image that will be used
  ansible.builtin.debug:
    msg: >-
      Selected image available as '{{ sle_micro_image.cached }}'
